package com.bluemob.app.guide

/*
 * GENERATED from web/src/features.js by `node tools/gen_guide.js`. Don't edit by hand.
 * General guidance written for BlueMob, not medical advice.
 */

/** One short survival guide, stored in the app so it works with no signal. */
data class Article(
    val id: String,
    val category: GuideCategory,
    val title: String,
    val minutes: Int,
    val intro: String,
    val steps: List<String>,
    val avoid: List<String>,
)

object GuideContent {
    val articles: List<Article> = listOf(
        Article(
            id = "cpr",
            category = GuideCategory.FIRST_AID,
            title = "CPR for an adult",
            minutes = 3,
            intro = "Use when someone is unresponsive and not breathing normally.",
            steps = listOf(
                "Check the area is safe. Tap their shoulders and shout. Look for normal breathing for no more than 10 seconds.",
                "Send someone to call emergency services and find a defibrillator (AED), or use BlueMob to reach someone with signal.",
                "Kneel beside them. Put the heel of one hand in the centre of the chest, other hand on top, arms straight.",
                "Push hard and fast: 5 to 6 cm deep, 100 to 120 pushes a minute. Let the chest rise fully between pushes.",
                "If you are trained, give 2 rescue breaths after every 30 pushes. If not, keep pushing without stopping.",
                "Keep going until help takes over, an AED tells you to stop, or they start breathing normally.",
            ),
            avoid = listOf(
                "Don't stop to check for a pulse unless they start breathing.",
                "Don't give up early. Swap with someone every 2 minutes if you can.",
            ),
        ),
        Article(
            id = "bleed",
            category = GuideCategory.FIRST_AID,
            title = "Severe bleeding",
            minutes = 2,
            intro = "Fast action matters most. Pressure stops most bleeding.",
            steps = listOf(
                "Protect yourself with gloves or a plastic bag if you can.",
                "Press firmly on the wound with a clean cloth or your hand. Keep pressing.",
                "If blood soaks through, add more cloth on top. Keep the first layer in place.",
                "Wrap a bandage tightly over the pad to hold pressure.",
                "For life-threatening bleeding from an arm or leg that won't stop, tie a tourniquet 5 to 7 cm above the wound, not on a joint. Tighten until bleeding stops and note the time.",
                "Keep them warm and lying down. Get medical help.",
            ),
            avoid = listOf(
                "Don't remove soaked dressings.",
                "Don't loosen a tourniquet once it is on.",
            ),
        ),
        Article(
            id = "burns",
            category = GuideCategory.FIRST_AID,
            title = "Burns",
            minutes = 2,
            intro = "Cool the burn quickly and for long enough.",
            steps = listOf(
                "Move away from the heat source.",
                "Cool the burn under cool running water for 20 minutes.",
                "Remove rings, watches or clothing near the burn, unless stuck to the skin.",
                "Cover loosely with cling film or a clean, non-fluffy cloth.",
                "Get medical help for burns larger than their hand, or on the face, hands, feet or groin, and for chemical or electrical burns.",
            ),
            avoid = listOf(
                "No ice, butter, oil or toothpaste.",
                "Don't burst blisters.",
            ),
        ),
        Article(
            id = "choke",
            category = GuideCategory.FIRST_AID,
            title = "Choking adult",
            minutes = 2,
            intro = "If they can cough, encourage them to keep coughing.",
            steps = listOf(
                "If they can't cough, speak or breathe, stand behind them and lean them forward.",
                "Give up to 5 firm back blows between the shoulder blades with the heel of your hand.",
                "If that fails, give up to 5 abdominal thrusts: fist above the belly button, pull sharply in and up.",
                "Repeat 5 back blows and 5 thrusts until the object comes out.",
                "If they become unresponsive, start CPR and get help.",
            ),
            avoid = emptyList(),
        ),
        Article(
            id = "hypo",
            category = GuideCategory.FIRST_AID,
            title = "Hypothermia (too cold)",
            minutes = 2,
            intro = "Signs: strong shivering, confusion, slurred speech, clumsiness, drowsiness.",
            steps = listOf(
                "Get them out of wind and wet, into shelter.",
                "Replace wet clothes with dry ones. Insulate them from the ground.",
                "Warm the body core first (chest, neck, groin) with blankets, a sleeping bag or skin-to-skin contact.",
                "If they are alert and can swallow, give warm, sweet drinks.",
                "Handle them gently and get medical help.",
            ),
            avoid = listOf(
                "No alcohol.",
                "Don't rub their arms and legs.",
                "Don't put them in a hot bath.",
            ),
        ),
        Article(
            id = "heat",
            category = GuideCategory.FIRST_AID,
            title = "Heat stroke",
            minutes = 2,
            intro = "An emergency. Signs: hot skin, confusion, fast pulse, sometimes no sweating.",
            steps = listOf(
                "Move them to shade and get help.",
                "Cool them fast: wet their skin and fan them.",
                "Put cold packs or wet cloths on the neck, armpits and groin.",
                "If they are awake, give small sips of water.",
                "Keep cooling until help arrives or they feel normal.",
            ),
            avoid = emptyList(),
        ),
        Article(
            id = "snake",
            category = GuideCategory.FIRST_AID,
            title = "Snake bite",
            minutes = 2,
            intro = "Most bites are not fatal. Calm and stillness help.",
            steps = listOf(
                "Move away from the snake. Keep the person calm and still.",
                "Keep the bitten limb still and remove rings, watches and tight clothing.",
                "Note the time and what the snake looked like. Don't try to catch it.",
                "Get to medical help as soon as possible. Carry them if you can.",
            ),
            avoid = listOf(
                "Don't cut the wound or try to suck out venom.",
                "Don't use ice or a tight tourniquet.",
            ),
        ),
        Article(
            id = "fracture",
            category = GuideCategory.FIRST_AID,
            title = "Broken bones and sprains",
            minutes = 2,
            intro = "Support the injury in the position you found it.",
            steps = listOf(
                "Keep the injured part still. Don't try to straighten it.",
                "Splint it with padding, using sticks or a rolled mat, covering the joint above and below.",
                "Check the skin beyond the injury stays warm and pink.",
                "For sprains: rest, a cold pack wrapped in cloth for 20 minutes, light compression, and raise it.",
                "Get medical help for suspected breaks.",
            ),
            avoid = emptyList(),
        ),
        Article(
            id = "find-water",
            category = GuideCategory.WATER,
            title = "Finding water",
            minutes = 2,
            intro = "You can last about 3 days without water. Find it early.",
            steps = listOf(
                "Walk downhill: valleys and low ground often hold streams.",
                "Look for green plants, insects and animal tracks. Birds often fly to water at dawn and dusk.",
                "Collect rain with any sheet or container.",
                "At dawn, wipe dew off grass with a cloth and wring it out.",
                "Treat all water before drinking.",
            ),
            avoid = listOf(
                "Don't drink seawater or urine.",
                "Avoid still, smelly water if anything better exists.",
            ),
        ),
        Article(
            id = "purify",
            category = GuideCategory.WATER,
            title = "Making water safe",
            minutes = 2,
            intro = "Boiling is the most reliable method.",
            steps = listOf(
                "If water is cloudy, let it settle, then pour it through a cloth.",
                "Bring it to a rolling boil for 1 minute (3 minutes above 2,000 m).",
                "Or use purification tablets, following the packet instructions.",
                "No fuel? Fill clear plastic bottles and leave them in full sun for 6 hours (2 days if cloudy).",
                "Store treated water in clean, covered containers.",
            ),
            avoid = emptyList(),
        ),
        Article(
            id = "fire",
            category = GuideCategory.FIRE,
            title = "Lighting a fire safely",
            minutes = 3,
            intro = "A fire needs three things: heat, fuel and air.",
            steps = listOf(
                "Pick a spot out of the wind, away from trees and tents. Clear 3 m of ground down to soil.",
                "Gather everything first: tinder (dry grass, bark), kindling (pencil-thick sticks) and fuel (wrist-thick wood).",
                "Make a loose tinder nest. Lean kindling over it like a tent, leaving gaps for air.",
                "Light the tinder from the windward side and blow gently at the base.",
                "Add bigger wood slowly as the flames grow.",
                "To put it out: drown it, stir it, and drown again until it's cold to the touch.",
            ),
            avoid = listOf(
                "Never leave a fire alone.",
                "Don't use petrol to start a fire.",
            ),
        ),
        Article(
            id = "shelter",
            category = GuideCategory.SHELTER,
            title = "Emergency shelter",
            minutes = 3,
            intro = "In bad weather, cold can harm you in hours. Shelter comes before food.",
            steps = listOf(
                "Choose dry, flat ground out of the wind. Avoid dry riverbeds and dead trees overhead.",
                "Insulate yourself from the ground first: you lose most heat there. Use branches, leaves or a mat.",
                "Keep it small, so your body heat warms it.",
                "Lean-to: prop a long branch against a tree and layer sticks, then leaves, on the windward side.",
                "Stay dry. Wet clothes lose most of their warmth.",
            ),
            avoid = emptyList(),
        ),
        Article(
            id = "north",
            category = GuideCategory.NAVIGATION,
            title = "Find north without a compass",
            minutes = 3,
            intro = "Simple ways to find your direction.",
            steps = listOf(
                "Shadow stick: put a stick upright and mark the tip of its shadow. Wait 15 minutes and mark again. A line from the first mark to the second points roughly east.",
                "The sun rises in the east and sets in the west. At midday it is due south in the northern hemisphere, due north in the southern.",
                "At night (north): find the Big Dipper. Its two end stars point to Polaris, the North Star.",
                "At night (south): extend the long axis of the Southern Cross about 4.5 times to find roughly south.",
            ),
            avoid = emptyList(),
        ),
        Article(
            id = "lost",
            category = GuideCategory.NAVIGATION,
            title = "If you are lost",
            minutes = 2,
            intro = "Remember STOP: Stop, Think, Observe, Plan.",
            steps = listOf(
                "Stop moving. Sit down, drink water and calm down.",
                "Think about how you got here and the last place you were sure of.",
                "Observe: landmarks, the sun, streams, your trail on the BlueMob compass.",
                "Plan: if people know your route, stay put and make yourself visible. Searchers find people who stay still.",
                "Use BlueMob to reach anyone nearby, and save your battery with Survival power.",
            ),
            avoid = emptyList(),
        ),
        Article(
            id = "signals",
            category = GuideCategory.SIGNALS,
            title = "Signalling for rescue",
            minutes = 2,
            intro = "Three of anything means 'help'.",
            steps = listOf(
                "Three fires, three whistle blasts or three flashes in a triangle or row signal distress.",
                "SOS in Morse code: three short, three long, three short ( ··· ––– ··· ). BlueMob's SOS light flashes it for you.",
                "Make ground signals big (3 m or more) and in contrast with the ground: V means 'need help', X means 'need medical help'.",
                "Flash a mirror or phone screen at aircraft or distant people.",
                "Wear or spread bright clothing in open ground.",
            ),
            avoid = emptyList(),
        ),
        Article(
            id = "help-sos",
            category = GuideCategory.SIGNALS,
            title = "Someone sent an SOS: how to help",
            minutes = 3,
            intro = "You may be the fastest help they have. Stay safe yourself first.",
            steps = listOf(
                "Reply at once so they know someone is coming. BlueMob's \"I'm coming\" button does this.",
                "BlueMob passes their SOS on to anyone with internet automatically. Keep the mesh on so it can.",
                "Check it's safe for you to go: weather, light, terrain. Don't become a second person who needs rescue.",
                "Tell someone near you where you're going, and go in pairs if you can.",
                "Take water, a warm layer, a light, and a first-aid kit if you have one.",
                "Follow the compass to them. BlueMob shows their direction and distance.",
                "When you reach them: check for danger, then whether they respond and are breathing. Use the first-aid guides.",
                "Keep them warm and still. Don't move someone who may have a neck or back injury unless they are in danger.",
                "Stay with them and send updates to the group until help arrives.",
            ),
            avoid = listOf(
                "Don't rush in alone at night or in a storm.",
                "Don't give them food or drink if they may need surgery or are barely conscious.",
            ),
        ),
        Article(
            id = "lightning",
            category = GuideCategory.WEATHER,
            title = "Lightning safety",
            minutes = 2,
            intro = "If you hear thunder, you are close enough to be struck.",
            steps = listOf(
                "30-30 rule: if thunder follows the flash within 30 seconds, take shelter. Wait 30 minutes after the last thunder.",
                "Go to a building or a hard-topped vehicle if you can.",
                "Outdoors: leave summits, ridges, open fields and water. Keep away from lone trees and metal fences.",
                "If caught in the open, crouch low on the balls of your feet, feet together, head tucked.",
                "In a group, spread out at least 15 m apart.",
            ),
            avoid = emptyList(),
        ),
        Article(
            id = "quake",
            category = GuideCategory.DISASTERS,
            title = "Earthquake",
            minutes = 2,
            intro = "Drop, Cover, Hold on.",
            steps = listOf(
                "Drop to your hands and knees.",
                "Cover your head and neck under a sturdy table, or next to an inside wall.",
                "Hold on until the shaking stops.",
                "If outside, move to open ground away from buildings, trees and power lines.",
                "After: expect aftershocks, check for gas smells, and avoid lifts and damaged buildings.",
            ),
            avoid = emptyList(),
        ),
        Article(
            id = "flood",
            category = GuideCategory.DISASTERS,
            title = "Floods",
            minutes = 2,
            intro = "Moving water is far more powerful than it looks.",
            steps = listOf(
                "Move to higher ground straight away.",
                "Never walk, swim or drive through flood water. 15 cm of moving water can knock you down, 30 cm can sweep a car away.",
                "Stay away from rivers, streams and drains.",
                "If trapped in a building, go to the highest floor, not a closed attic.",
                "Use BlueMob to tell others where you are.",
            ),
            avoid = emptyList(),
        ),
        Article(
            id = "battery-low",
            category = GuideCategory.BASICS,
            title = "Phone battery critically low",
            minutes = 2,
            intro = "At 1 to 5%, every minute of battery counts. Spend it on what keeps you safe.",
            steps = listOf(
                "If you may need help, send your SOS now while you still can. Add a short note: where you are and what's wrong.",
                "Send one short message to your group: where you are, where you're heading, and when you'll switch the phone on next.",
                "Turn on Battery Saver, set the screen to its lowest brightness, and close every other app.",
                "Turn on airplane mode so the phone stops searching for signal. If you need BlueMob, turn Bluetooth back on.",
                "Switch the phone off completely. Turn it on only at agreed times, for example every 2 hours on the hour, to check messages.",
                "Keep the phone warm in an inner pocket or sleeping bag. Cold drains batteries fast, and a cold \"dead\" phone often wakes up once warm.",
                "Use other ways to be found: 3 whistle blasts, a mirror, bright clothing, or a smoky fire in the open.",
            ),
            avoid = listOf(
                "Don't leave the screen on for the compass or the map. Check, then switch off.",
                "Don't wait until 0% to send your SOS.",
            ),
        ),
        Article(
            id = "recharge",
            category = GuideCategory.BASICS,
            title = "Getting power back without a socket",
            minutes = 2,
            intro = "Ways to recharge a phone far from a wall socket.",
            steps = listOf(
                "Power bank: the most reliable option. Charge it fully before every trip.",
                "Vehicle: a USB car charger works while the engine runs. Many cars, buses and bikes have USB sockets.",
                "Solar charger: point the panel straight at the sun. Charge a power bank with it, then the phone. Cloud makes it very slow.",
                "Hand-crank or dynamo chargers (in some radios and torches) give small top-ups. Crank steadily rather than fast.",
                "Ask people nearby for a power bank or the right cable. Charge the phone your group relies on for SOS first.",
                "Warm a cold battery slowly against your body before charging. Batteries charge poorly when very cold.",
            ),
            avoid = listOf(
                "Don't heat the phone on a fire, a stove or in strong direct sun.",
                "Don't open, bend or puncture the battery.",
            ),
        ),
        Article(
            id = "threes",
            category = GuideCategory.BASICS,
            title = "The rule of threes",
            minutes = 1,
            intro = "What to deal with first. Roughly, you can survive:",
            steps = listOf(
                "3 minutes without air.",
                "3 hours without shelter in harsh weather.",
                "3 days without water.",
                "3 weeks without food.",
                "So: breathing and bleeding first, then shelter and warmth, then water, then food.",
            ),
            avoid = listOf(
                "Don't eat plants or mushrooms you can't identify with certainty.",
            ),
        ),
    )

    /** Built-in guides plus the packs downloaded on this phone. */
    fun all(): List<Article> = articles + GuidePacks.installedArticles
    fun byId(id: String): Article? = all().firstOrNull { it.id == id }
}
